# Generated by Django 4.2.6 on 2024-04-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_name', models.CharField(max_length=20)),
                ('Contact_No', models.IntegerField()),
                ('DOB', models.IntegerField()),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
    ]
